//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetterReviews.Database.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessReview
    {
        public int Id { get; set; }
        public int BusinessId { get; set; }
        public int Rating { get; set; }
        public string Review { get; set; }
        public System.DateTime SubmittedDate { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> ReviewResponseId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual AspNetUser AspNetUser2 { get; set; }
        public virtual Business Business { get; set; }
        public virtual ReviewReponse ReviewReponse { get; set; }
    }
}
