//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetterReviews.Database.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public string UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Nickname { get; set; }
        public Nullable<int> AddressId { get; set; }
        public string PhoneNumber { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
